title: Pandaful

remote_theme: sighingnow/jekyll-gitbook

plugins:
    - jekyll-sitemap
    - jekyll-remote-theme

permalink: /:categories/:year-:month-:day-:title:output_ext

ordered_collections:
  - posts
  - pages
  - recommend