title: Pandaful

remote_theme: sighingnow/jekyll-gitbook

url:              'https://pandaful-2312.github.io'
baseurl:          '/pages'

plugins:
    - jekyll-sitemap
    - jekyll-remote-theme
    - jekyll-feed
    - jekyll-readme-index
    - jemoji

rss: RSS
toc:
  enabled: true
  h_min:   1
  h_max:   3

permalink: /:categories/:year-:month-:day-:title:output_ext

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/
  recommend:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - pages
  - recommend