title: Pandaful

theme: minima

header_pages:
  - recommend/recommend.md
  - marks/marks.md

plugins:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-remote-theme
    - jekyll-seo-tag

minima:
  skin: auto