title: Pandaful

remote_theme: sighingnow/jekyll-gitbook

plugins:
    - jekyll-sitemap
    - jekyll-remote-theme
    - jekyll-feed
    - jekyll-readme-index
    - jemoji

rss: RSS

permalink: /:categories/:year-:month-:day-:title:output_ext

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/
  recommend:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - pages
  - recommend