title: Pandaful

remote_theme: sighingnow/jekyll-gitbook

url:              'https://pandaful-2312.github.io'
baseurl:          '/pages'

plugins:
    - jekyll-sitemap
    - jekyll-remote-theme
    - jekyll-feed
    - jekyll-readme-index
    - jemoji
